spring:
  datasource :
    url : jdbc:h2:mem:testdb
    username: sa
  h2 :
    console :
      enabled : true
  jpa:
    show-sql : true
    properties :
      hibernate:
        format_sql:true
    defer-datasource-initialization : true
jwt:
  issuer : ajufresh@gmail.com
  secret_key : study-springboot
security :
  oauth2:
    client:
      registration:
        google:
